{
  "npm-intellisense.scanDevDependencies": true,
  "auto-close-tag.SublimeText3Mode": true,
  "window.zoomLevel": -2,
  "editor.fontSize": 19,
  "editor.renderIndentGuides": true,
  "editor.formatOnType": true,
"editor.fontFamily": "Input",
 // "editor.fontFamily": "Fira Code Regular",
  "editor.fontLigatures": true,
  "editor.mouseWheelZoom": true,
  "typescript.check.tscVersion": false,
  "vsicons.projectDetection.autoReload": true,
  "editor.tabCompletion": true,
  "editor.acceptSuggestionOnEnter": false,
  "editor.minimap.enabled": true,
  "editor.minimap.renderCharacters": false,
  "workbench.colorTheme": "Oceanic Next Italic",
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "vsicons.dontShowNewVersionMessage": true,
  "spell.StopAsking": true,
  "emmet.useNewEmmet": false,
  "workbench.startupEditor": "newUntitledFile",
  "eslint.autoFixOnSave": true,
  "prettier.eslintIntegration": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "files.eol": "\n",
  "workbench.iconTheme": "vscode-icons",
  "gitlens.advanced.messages": {
    "suppressCommitHasNoPreviousCommitWarning": false,
    "suppressCommitNotFoundWarning": false,
    "suppressFileNotUnderSourceControlWarning": false,
    "suppressGitVersionWarning": false,
    "suppressLineUncommittedWarning": false,
    "suppressNoRepositoryWarning": false,
    "suppressResultsExplorerNotice": false,
    "suppressShowKeyBindingsNotice": true
  }
}
